[
  {
    "keyword": "Feature",
    "name": "Touches API automation",
    "line": 2,
    "id": "touches-api-automation",
    "tags": [
      {
        "name": "@api-testing",
        "line": 1
      }
    ],
    "uri": "apis.feature",
    "elements": [
      {
        "id": "touches-api-automation;using-a-valid-auth0-token-and-fetching-all-touches-of-a-user",
        "keyword": "Scenario",
        "line": 4,
        "name": "Using a valid Auth0 token and fetching all touches of a user",
        "tags": [
          {
            "name": "@api-testing",
            "line": 1
          }
        ],
        "type": "scenario",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 5,
            "name": "I generate auth0 token",
            "result": {
              "status": "failed",
              "duration": 5253000000,
              "error_message": "CypressError: `cy.request()` failed trying to load:\n\nhttps://undefined.sendoso.com/api/v3/me\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo ENOTFOUND undefined.sendoso.com\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: https://undefined.sendoso.com/api/v3/me\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer\n\nhttps://on.cypress.io/request\n    at http://localhost:60676/__cypress/runner/cypress_runner.js:158965:19\n    at tryCatcher (http://localhost:60676/__cypress/runner/cypress_runner.js:10325:23)\n    at http://localhost:60676/__cypress/runner/cypress_runner.js:5464:37\n    at tryCatcher (http://localhost:60676/__cypress/runner/cypress_runner.js:10325:23)\n    at Promise._settlePromiseFromHandler (http://localhost:60676/__cypress/runner/cypress_runner.js:8260:31)\n    at Promise._settlePromise (http://localhost:60676/__cypress/runner/cypress_runner.js:8317:18)\n    at Promise._settlePromise0 (http://localhost:60676/__cypress/runner/cypress_runner.js:8362:10)\n    at Promise._settlePromises (http://localhost:60676/__cypress/runner/cypress_runner.js:8438:18)\n    at _drainQueueStep (http://localhost:60676/__cypress/runner/cypress_runner.js:5032:12)\n    at _drainQueue (http://localhost:60676/__cypress/runner/cypress_runner.js:5025:9)\n    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:60676/__cypress/runner/cypress_runner.js:5041:5)\n    at Async.drainQueues (http://localhost:60676/__cypress/runner/cypress_runner.js:4911:14)\nFrom Your Spec Code:\n    at Context.eval (http://localhost:60676/__cypress/tests?p=cypress/integration/apis.feature:349:12)\n\nFrom Node.js Internals:\n  RequestError: Error: getaddrinfo ENOTFOUND undefined.sendoso.com\n      at new RequestError (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n      at Request.plumbing.callback (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n      at Request.RP$callback [as _callback] (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n      at self.callback (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:185:22)\n      at Request.emit (events.js:310:20)\n      at Request.onRequestError (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:877:8)\n      at ClientRequest.emit (events.js:322:22)\n      at TLSSocket.socketErrorListener (_http_client.js:426:9)\n      at TLSSocket.emit (events.js:310:20)\n      at emitErrorNT (internal/streams/destroy.js:92:8)\n      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n      at processTicksAndRejections (internal/process/task_queues.js:84:21)\n  \nFrom Your Spec Code:\n    at Context.eval (http://localhost:60676/__cypress/tests?p=cypress/integration/apis.feature:349:12)"
            }
          },
          {
            "arguments": [],
            "keyword": "Then ",
            "line": 6,
            "name": "I hit the get all touches endpoint and verify its response",
            "result": {
              "status": "skipped"
            }
          }
        ]
      },
      {
        "id": "touches-api-automation;sending-an-egift-touch-via-send-api",
        "keyword": "Scenario",
        "line": 8,
        "name": "Sending an eGift touch via send API",
        "tags": [
          {
            "name": "@api-testing",
            "line": 1
          }
        ],
        "type": "scenario",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 9,
            "name": "I generate auth0 token",
            "result": {
              "status": "failed",
              "duration": 5521000000,
              "error_message": "CypressError: `cy.request()` failed trying to load:\n\nhttps://undefined.sendoso.com/api/v3/me\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo ENOTFOUND undefined.sendoso.com\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: https://undefined.sendoso.com/api/v3/me\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer\n\nhttps://on.cypress.io/request\n    at http://localhost:60676/__cypress/runner/cypress_runner.js:158965:19\n    at tryCatcher (http://localhost:60676/__cypress/runner/cypress_runner.js:10325:23)\n    at http://localhost:60676/__cypress/runner/cypress_runner.js:5464:37\n    at tryCatcher (http://localhost:60676/__cypress/runner/cypress_runner.js:10325:23)\n    at Promise._settlePromiseFromHandler (http://localhost:60676/__cypress/runner/cypress_runner.js:8260:31)\n    at Promise._settlePromise (http://localhost:60676/__cypress/runner/cypress_runner.js:8317:18)\n    at Promise._settlePromise0 (http://localhost:60676/__cypress/runner/cypress_runner.js:8362:10)\n    at Promise._settlePromises (http://localhost:60676/__cypress/runner/cypress_runner.js:8438:18)\n    at _drainQueueStep (http://localhost:60676/__cypress/runner/cypress_runner.js:5032:12)\n    at _drainQueue (http://localhost:60676/__cypress/runner/cypress_runner.js:5025:9)\n    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:60676/__cypress/runner/cypress_runner.js:5041:5)\n    at Async.drainQueues (http://localhost:60676/__cypress/runner/cypress_runner.js:4911:14)\nFrom Your Spec Code:\n    at Context.eval (http://localhost:60676/__cypress/tests?p=cypress/integration/apis.feature:349:12)\n\nFrom Node.js Internals:\n  RequestError: Error: getaddrinfo ENOTFOUND undefined.sendoso.com\n      at new RequestError (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n      at Request.plumbing.callback (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n      at Request.RP$callback [as _callback] (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n      at self.callback (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:185:22)\n      at Request.emit (events.js:310:20)\n      at Request.onRequestError (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:877:8)\n      at ClientRequest.emit (events.js:322:22)\n      at TLSSocket.socketErrorListener (_http_client.js:426:9)\n      at TLSSocket.emit (events.js:310:20)\n      at emitErrorNT (internal/streams/destroy.js:92:8)\n      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n      at processTicksAndRejections (internal/process/task_queues.js:84:21)\n  \nFrom Your Spec Code:\n    at Context.eval (http://localhost:60676/__cypress/tests?p=cypress/integration/apis.feature:349:12)"
            }
          },
          {
            "arguments": [],
            "keyword": "Then ",
            "line": 10,
            "name": "I send a touch \"61383\" and verify response",
            "result": {
              "status": "skipped"
            }
          }
        ]
      },
      {
        "id": "touches-api-automation;sending-a-physical-touch-via-send-api",
        "keyword": "Scenario",
        "line": 12,
        "name": "Sending a physical touch via send API",
        "tags": [
          {
            "name": "@api-testing",
            "line": 1
          }
        ],
        "type": "scenario",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 13,
            "name": "I generate auth0 token",
            "result": {
              "status": "failed",
              "duration": 5463000000,
              "error_message": "CypressError: `cy.request()` failed trying to load:\n\nhttps://undefined.sendoso.com/api/v3/me\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: getaddrinfo ENOTFOUND undefined.sendoso.com\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: https://undefined.sendoso.com/api/v3/me\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer\n\nhttps://on.cypress.io/request\n    at http://localhost:60676/__cypress/runner/cypress_runner.js:158965:19\n    at tryCatcher (http://localhost:60676/__cypress/runner/cypress_runner.js:10325:23)\n    at http://localhost:60676/__cypress/runner/cypress_runner.js:5464:37\n    at tryCatcher (http://localhost:60676/__cypress/runner/cypress_runner.js:10325:23)\n    at Promise._settlePromiseFromHandler (http://localhost:60676/__cypress/runner/cypress_runner.js:8260:31)\n    at Promise._settlePromise (http://localhost:60676/__cypress/runner/cypress_runner.js:8317:18)\n    at Promise._settlePromise0 (http://localhost:60676/__cypress/runner/cypress_runner.js:8362:10)\n    at Promise._settlePromises (http://localhost:60676/__cypress/runner/cypress_runner.js:8438:18)\n    at _drainQueueStep (http://localhost:60676/__cypress/runner/cypress_runner.js:5032:12)\n    at _drainQueue (http://localhost:60676/__cypress/runner/cypress_runner.js:5025:9)\n    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:60676/__cypress/runner/cypress_runner.js:5041:5)\n    at Async.drainQueues (http://localhost:60676/__cypress/runner/cypress_runner.js:4911:14)\nFrom Your Spec Code:\n    at Context.eval (http://localhost:60676/__cypress/tests?p=cypress/integration/apis.feature:349:12)\n\nFrom Node.js Internals:\n  RequestError: Error: getaddrinfo ENOTFOUND undefined.sendoso.com\n      at new RequestError (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n      at Request.plumbing.callback (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n      at Request.RP$callback [as _callback] (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n      at self.callback (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:185:22)\n      at Request.emit (events.js:310:20)\n      at Request.onRequestError (/Users/Abubakr/Library/Caches/Cypress/5.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:877:8)\n      at ClientRequest.emit (events.js:322:22)\n      at TLSSocket.socketErrorListener (_http_client.js:426:9)\n      at TLSSocket.emit (events.js:310:20)\n      at emitErrorNT (internal/streams/destroy.js:92:8)\n      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n      at processTicksAndRejections (internal/process/task_queues.js:84:21)\n  \nFrom Your Spec Code:\n    at Context.eval (http://localhost:60676/__cypress/tests?p=cypress/integration/apis.feature:349:12)"
            }
          },
          {
            "arguments": [],
            "keyword": "Then ",
            "line": 14,
            "name": "I send a physical touch \"61310\" and verify response",
            "result": {
              "status": "skipped"
            }
          }
        ]
      }
    ]
  }
]